#!/bin/sh -eu

remote="$1"
url="$2"

echo "remote: $remote"
echo "url:    $url"

while read local_ref local_sha remote_ref remote_sha
do
    echo "'$local_ref' '$local_sha' '$remote_ref' '$remote_sha'"
done

exit 1
